"""
Constants for Adaptive UI System
Centralized configuration constants to avoid magic numbers
"""

# Display Constants
GAZE_TRAIL_LENGTH = 15  # Number of gaze points to show in trail
POINTER_STATIC_THRESHOLD_FRAMES = 90  # Frames before warning (~3 seconds at 30fps)
POINTER_STATIC_WARNING_SECONDS = 3.0  # Seconds for static pointer warning

# Pointer Visualization
POINTER_OUTER_RADIUS = 60
POINTER_MIDDLE_RADIUS = 45
POINTER_INNER_RADIUS = 30
POINTER_CENTER_RADIUS = 15
POINTER_DOT_RADIUS = 8
POINTER_CROSSHAIR_LENGTH = 80
POINTER_CROSSHAIR_THICKNESS = 4
POINTER_INDICATOR_SIZE = 120  # Size of the indicator showing gaze point

# Text Display Positions (y-coordinates)
TEXT_Y_EMOTION = 30
TEXT_Y_COGNITIVE_LOAD = 60
TEXT_Y_TRIGGERS = 90
TEXT_Y_ADAPTATIONS = 120
TEXT_Y_WARNING = 30  # From bottom

# Text Formatting
TEXT_MARGIN_X = 10
TEXT_MARGIN_TOP_RIGHT = 10
TEXT_FONT = 0  # cv2.FONT_HERSHEY_SIMPLEX
TEXT_FONT_SCALE_LARGE = 0.7
TEXT_FONT_SCALE_MEDIUM = 0.6
TEXT_FONT_SCALE_SMALL = 0.5
TEXT_THICKNESS_BOLD = 2
TEXT_THICKNESS_NORMAL = 1

# Colors (BGR format for OpenCV)
COLOR_GREEN = (0, 255, 0)
COLOR_RED = (0, 0, 255)
COLOR_YELLOW = (0, 255, 255)
COLOR_WHITE = (255, 255, 255)
COLOR_GRAY = (200, 200, 200)
COLOR_CYAN = (255, 255, 0)
COLOR_BLACK = (0, 0, 0)
COLOR_LIGHT_GREEN = (0, 255, 100)
COLOR_ADAPTATION = (255, 255, 0)

# Gaze Tracking
GAZE_SENSITIVITY_SCALE_X = 6.0
GAZE_SENSITIVITY_SCALE_Y = 6.0

# Frame Processing
DEFAULT_TARGET_FPS = 30
MIN_FRAME_INTERVAL_MS = 33  # ~30 FPS (1000ms / 30)

# Emotion Detection
FACE_DETECTION_SCALE_FACTOR = 1.1
FACE_DETECTION_MIN_NEIGHBORS = 3
FACE_DETECTION_MIN_SIZE = (30, 30)
FACE_ROI_PADDING = 20
FACE_RESIZE_TARGET = (48, 48)

# Cognitive Load
COGNITIVE_LOAD_OVERLOAD_THRESHOLD = 0.6
GAZE_WANDER_WEIGHT = 0.3
FIXATION_DURATION_WEIGHT = 0.4
NEGATIVE_AFFECT_WEIGHT = 0.3

# Camera Test
CAMERA_TEST_POSITION_THRESHOLD = 2  # pixels
